@startuml UC3
autonumber "<b>[0]"
participant Apotheke as Ap #LightGreen
participant Arzt as A #LightYellow
participant Pflegeeinrichtung as PE #LightBlue

Ap -> A++: <b>Rezeptanforderung\n <i>ERPServiceRequestPrescriptionRequest  \n.status = #active \n.basedOn = ERPServiceRequestMedicationRequest
Ap --> PE:  <b>Nachrichten_Kopie\n <i>ERPServiceRequestPrescriptionRequest
A -> A: E-Rezept einstellen
A -> Ap--: <b>Rezeptanforderung_Bestätigung\n <i>ERPServiceRequestPrescriptionRequest  \n.status = #completed \n.basedOn = KBV_Prescription
Ap --> PE:  <b>Nachrichten_Kopie\n <i>ERPServiceRequestPrescriptionRequest
@enduml