@startuml "multiple-request-diagram-2"
package "MessageBundle" {


  class MessageHeader {
      sender: string
      recipient: string
      eventcode: string
      focus: reference<ServiceRequest>
  }

  class ServiceRequest1 {
      id: #id-1
      requisition: #group-1
      basedOn: reference<MedicationRequest>
      subject: reference<Patient>
  }

  class ServiceRequest2 {
      id: #id-2
      requisition: #group-1
      basedOn: reference<MedicationRequest>
      subject: reference<Patient>
  }

  class Patient1 {
      id: string
      name: string
  }

  class Patient2 {
      id: string
      name: string
  }

  class MedicationRequest {
      id: string
      medicationCodeableConcept: string
  }

}

MessageHeader ..> ServiceRequest1
MessageHeader ..> ServiceRequest2
ServiceRequest1 ..> Patient1
ServiceRequest1 ..> MedicationRequest
ServiceRequest2 ..> Patient2
ServiceRequest2 ..> MedicationRequest

@enduml