@startuml name = "UC3-Rezeptanforderung-Apotheke"


skinparam maxMessageSize 200

actor Apotheke
actor "Verordnender \nLeistungserbringer" as Arztpraxis
actor "Pflegeeinrichtung" as Pflegeeinrichtung

title UC3-Rezeptanforderung der heimversorgenden Apotheke
hide footbox
autonumber "<b>[0]"

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Medikamentabgabe|
endlegend

Apotheke -> Arztpraxis: //Rezeptanforderung//
Apotheke --> Pflegeeinrichtung: //ServiceRequest_Nachricht_Kopie//

opt #LightPink Stornierung
    Apotheke -> Arztpraxis: //Rezeptanforderung_Storno//
    Apotheke --> Pflegeeinrichtung: //ServiceRequest_Nachricht_Kopie//
    alt #LightPink E-Rezept noch nicht eingestellt
    Apotheke -[hidden]-> Arztpraxis: Rezeptanforderung wird verworfen
        Arztpraxis ->x Arztpraxis: Rezeptanforderung wird verworfen
    else #LightPink E-Rezept wurde eingestellt
        Arztpraxis ->x Arztpraxis: E-Rezept wird gelöscht
    end
end


alt #PaleGreen Arzt ist einverstanden 
    Arztpraxis -> Apotheke: //Rezeptanforderung_Bestätigung//
    Arztpraxis --> Pflegeeinrichtung: //ServiceRequest_Nachricht_Kopie//
    Apotheke -> Pflegeeinrichtung: //Dispensieranforderung_Bestätigung//
    Apotheke -> Pflegeeinrichtung: Medikamentenbelieferung

else #LightPink Arzt lehnt ab
    Arztpraxis -> Apotheke: //Rezeptanforderung_Ablehnung//
    Arztpraxis --> Pflegeeinrichtung: //ServiceRequest_Nachricht_Kopie//
end

@enduml