install:
  - firely_terminal
  - sushi
  - igpub
  - publishtools
deploy:
  env:
    dev: gematik_gemspec_fhir_dev-0
    prod: gematik_gemspec_fhir_prod-0
build:
  pipeline:
    - shell: ./scripts/generate-heading-links-js.sh
    - sushi
    - igpub
    - igpub_qa