@startuml


skinparam rectangle {
    roundCorner<<Concept>> 54
}
    rectangle "Legende" {
        rectangle "Fachobjekt aus Business-Sicht" as Fachobjekt #BUSINESS
        rectangle "Optionales Fachobjekt \naus Business-Sicht" as Fachobjekt_opt #LightSlateGrey
        rectangle "FHIR-Objekt, auf das gemappt \nwerden soll" as FHIR_objekt #APPLICATION
        rectangle "FHIR-Objekt, auf das gemappt \nwerden soll mit Kandidatenstatus" as FHIR_objekt_kandidat <<Candidate>> #APPLICATION
        rectangle "<font color=red>zusätzlich notwendiges, \n<font color=red>aber noch nicht bestätigtes \n<font color=red>Fachobjekt/Unterobjekt \n<font color=red>aus Business-Sicht" as Fachobjekt_zusaetzlich
    }


@enduml