@startuml name = "UC1-Rezeptanforderung-Versicherteninvolvierung"


skinparam maxMessageSize 200

actor "Pflegeeinrichtung" as Pflegeeinrichtung
actor "Verordnender \nLeistungserbringer" as Arztpraxis
actor Versicherter
actor Apotheke

title UC1-Rezeptanforderungen durch Pflegeeinrichtungen mit Abholung durch Versicherten
hide footbox
autonumber "<b>[0]"

Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//
Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Bestätigung//

opt Benachrichtigung des Versicherten
    Pflegeeinrichtung --> Versicherter: opt. Benachrichtigung über Ausstellung des E-Rezepts
end

Versicherter ->> Versicherter: Beziehen des E-Rezept Tokens

note left
    möglich via
        1. E-Rezept-App
        2. Vorlage der eGK in der Apotheke
        3. Papierausdruck
end note

Versicherter ->> Apotheke: Medikamentabholung
@enduml