@startuml name = "UC1-Rezeptanforderung-Pflege"

skinparam maxMessageSize 200

actor "Pflegeeinrichtung" as Pflegeeinrichtung
actor Apotheke
actor "Verordnender\nLeistungserbringer" as Arzt
entity "E-Rezept\nFachdienst" as FD

title UC1-Dispensieranforderung durch Pflegeeinrichtung
hide footbox
autonumber "<b>[0]"

Pflegeeinrichtung ->> Apotheke: //Dispensieranforderung_Rezeptübermittlung//

opt
 Apotheke -> Apotheke: Prüfung des E-Rezeptes Fehlgeschlagen
 Apotheke -> FD: E-Rezept zurückgeben
 group "Rezeptanforderung durch Apotheke"
  Apotheke -> Arzt: Anforderung
  Arzt -> FD: E-Rezept löschen
  Arzt -> Apotheke: E-Rezept Token
 end
end

Apotheke -> Apotheke: Einlösen des E-Rezeptes

Apotheke ->> Pflegeeinrichtung: //Dispensieranforderung_Bestätigung//
Apotheke ->> Pflegeeinrichtung: Medikamentbelieferung

@enduml