@startuml name = "UC1-Rezeptanforderung-Pflege"


skinparam maxMessageSize 200

box "Rezeptmanagement" #White
    actor "Pflegeeinrichtung" as Pflegeeinrichtung
end box
actor "Verordnender \nLeistungserbringer" as Arztpraxis

title UC1-Rezeptanforderung durch Pflegeeinrichtung
hide footbox
autonumber "<b>[0]"

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Medikamentabgabe|
endlegend

Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//

opt #LightPink Stornierung
    Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung_Storno//
    alt #LightPink E-Rezept noch nicht eingestellt
    Pflegeeinrichtung -[hidden]-> Arztpraxis: Rezeptanforderung wird verworfen
        Arztpraxis ->x Arztpraxis: Rezeptanforderung wird verworfen
    else #LightPink E-Rezept wurde eingestellt
        Arztpraxis ->x Arztpraxis: E-Rezept wird gelöscht
    end
end

alt #PaleGreen Arzt ist einverstanden 
    
    Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Rezeptübermittlung//
    
else #LightPink Arzt lehnt ab
    Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Storno//
end


@enduml