@startuml name = "UC2-Rezeptanforderung-Patienteninvolvierung"


skinparam maxMessageSize 200

actor "Pflegeeinrichtung" as Pflegeeinrichtung
actor "Verordnender \nLeistungserbringer" as Arztpraxis
actor Patient
actor Apotheke

title UC2-Rezeptanforderung der Pflege mit Einlösung durch Patient
hide footbox
autonumber "<b>[0]"

group "UC1-Rezeptanforderung durch Pflegeeinrichtung"
Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//

    opt #LightPink Stornierung
        Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung_Storno//
        alt #LightPink E-Rezept noch nicht eingestellt
        Pflegeeinrichtung -[hidden]-> Arztpraxis: Rezeptanforderung wird verworfen
            Arztpraxis ->x Arztpraxis: Rezeptanforderung wird verworfen
        else #LightPink E-Rezept wurde eingestellt
            Arztpraxis ->x Arztpraxis: E-Rezept wird gelöscht
        end
    end

Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Bestätigung//
end

opt Benachrichtigung des Patienten
    Pflegeeinrichtung --> Patient: opt. Benachrichtigung über Ausstellung des E-Rezepts
end

Patient ->> Patient: Beziehen des E-Rezept Tokens

note left
    möglich via
        1. E-Rezept-App
        2. Vorlage der eGK in der Apotheke
        3. Papierausdruck
end note

Patient ->> Apotheke: Medikamentabholung
@enduml