@startuml name = "Rezeptanforderung-Apotheke"


skinparam maxMessageSize 200

box "Rezeptmanagement" #White
    actor Apotheke
end box
actor "Pflegeeinrichtung \n(stationär)" as Pflegeeinrichtung
actor "Verordnender \nLeistungserbringer" as Arztpraxis

title Rezeptanforderungen durch (Rahmenvertrags-)Apotheken (fachliche Sicht)
hide footbox
autonumber

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Medikamentabgabe|
    **lfd.Nr.** //Informationseinheit als Nachricht übermittelt//
    **lfd.Nr.** **sonstige Aktivität**
endlegend

hnote over Apotheke, Pflegeeinrichtung
    Vorbedingung:
    Rahmenvertrag zwischen Apotheke & 
    Pflegedienst nach §12a ApoG
end hnote

Apotheke ->> Pflegeeinrichtung: //Rezeptanforderung//
Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//

opt #LightPink Stornierung
    Apotheke ->> Pflegeeinrichtung: //Rezeptanforderung_Storno//
    Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung_Storno//

    Arztpraxis ->x Arztpraxis: **Rezeptanforderung wird verworfen**
end

alt Rezeptanforderung liegt vor beim Verordnenden
    alt #PaleGreen Arzt ist einverstanden 
        Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Rezeptübermittlung//
        Pflegeeinrichtung ->> Apotheke: //Rezeptanforderung_Rezeptübermittlung//
        Apotheke ->> Pflegeeinrichtung: //Dispensieranforderung_Bestätigung//
        Apotheke ->> Pflegeeinrichtung: **Medikamentabgabe/-auslieferung**

    else #LightPink Arzt lehnt ab
        Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Storno//
        Pflegeeinrichtung ->> Apotheke: //Rezeptanforderung_Storno//
    end
end

@enduml