@startuml name = "UC3-Rezeptanforderung-anwendigungsfertige-Zytostatika"


skinparam maxMessageSize 300

title UC3-Rezeptanforderung für anwendungsfertige Zytostatika Zubereitungen
hide footbox
autonumber

    actor "Apotheke" as Apotheke

    actor "Verordnender \nLeistungserbringer" as Arzt

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Zubereitungs-/Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Zubereitungs-/Medikamentabgabe|
    **lfd.Nr.** //Informationseinheit als Nachricht übermittelt//
    **lfd.Nr.** **sonstige Aktivität**
endlegend

?-> Apotheke: Start der \nZubereitung

Apotheke ->> Apotheke: Zubereitungsdaten

Apotheke ->> Arzt: //Rezeptanforderung//

break #LightPink Stornierung notwendig
    Apotheke ->> Arzt: //Rezeptanforderung_Storno//
    Arzt ->x Arzt: **Rezeptanforderung wird verworfen**
    Arzt ->> Apotheke: //Stornierungsquittung//
end

Arzt ->> Arzt: **Arbeitslisteneintrag erzeugen und vorhalten**

Arzt ->> Arzt: **Rezeptzustimmung ODER Rezeptablehnung festlegen**

alt #PaleGreen Arzt stimmt Rezeptanforderung zu
    Arzt ->> Apotheke: //Rezeptanforderung_Rezeptuebermittlung//
else #LightPink Arzt lehnt Rezeptanforderung ab
    Arzt ->> Apotheke: //Rezeptanforderung_Ablehnung//

end

@enduml