@startuml name = "UC4-Rezeptanforderung-anwendigungsfertige-Zytostatika"


skinparam maxMessageSize 300

title UC4-Rezeptanforderung für anwendungsfertige Zytostatikazubereitungen
hide footbox
autonumber "<b>[0]"

    actor "Apotheke" as Apotheke
    actor "Verordnender \nLeistungserbringer" as Arzt

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Zubereitungs-/Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Zubereitungs-/Medikamentabgabe|
endlegend

?-> Apotheke: Start der \nZubereitung

Apotheke ->> Apotheke: Zubereitungsdaten

Apotheke ->> Arzt: //Rezeptanforderung//

break #LightPink Stornierung notwendig
    Apotheke ->> Arzt: //Rezeptanforderung_Storno//
    alt #LightPink E-Rezept noch nicht eingestellt
        Arzt ->x Arzt: Rezeptanforderung wird verworfen
    else #LightPink E-Rezept wurde eingestellt
        Arzt ->x Arzt: E-Rezept wird gelöscht
    end
end

alt #PaleGreen Arzt stimmt Rezeptanforderung zu
    Arzt ->> Apotheke: //Rezeptanforderung_Rezeptuebermittlung//
else #LightPink Arzt lehnt Rezeptanforderung ab
    Arzt ->> Apotheke: //Rezeptanforderung_Ablehnung//

end

@enduml