name: "💡 Feature Request"
description: Suggest an idea for this project.
title: "[FEATURE] <title>"
labels:
  - enhancement
assignees:
  - florianschoffke
body:
  - type: textarea
    id: problem-description
    attributes:
      label: "Problem Description"
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: "Desired Solution"
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: "Alternative Solutions"
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false