name: "☝️ Kommentierung für gemF_eRp_KIM 2.0.0"
description: Erstellen Sie einen Bericht, um uns bei der Verbesserung des Implementierungsleitfadens oder der FHIR-Profile zu helfen.
title: "[Kommentierung] <title>"
labels:
  - kommentierung
assignees:
  - florianschoffke
body:
  - type: textarea
    id: issue-description
    attributes:
      label: "Beschreibung des Problems"
      description: Beschreiben Sie das Problem oder den Kommentar zum Implementierungsleitfaden oder FHIR-Profil.
      placeholder: Eine klare und präzise Beschreibung des Problems oder Kommentars zum Implementierungsleitfaden oder FHIR-Profil.
    validations:
      required: true
  - type: input
    id: page-link
    attributes:
      label: "Seite des IG oder FHIR-Profils"
      description: Nennen Sie den Titel oder geben Sie einen Link zur betroffenen Seite des Implementierungsleitfadens oder FHIR-Profils an.
      placeholder: Geben Sie einen Link oder Titel der betroffenen Seite oder des FHIR-Profils an.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Vorschlag zur Verbesserung"
      description: Machen Sie Vorschläge zur Verbesserung des Implementierungsleitfadens oder FHIR-Profils.
      placeholder: Ein klarer und präziser Vorschlag zur Verbesserung des Implementierungsleitfadens oder FHIR-Profils.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: Fügen Sie gegebenenfalls Screenshots hinzu, um Ihr Problem oder Ihren Vorschlag zu erläutern.
      placeholder: Fügen Sie hier Screenshots hinzu.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Zusätzlicher Kontext"
      description: Fügen Sie hier weiteren Kontext oder Informationen zum Problem oder Vorschlag hinzu.
      placeholder: Fügen Sie hier weiteren Kontext oder Informationen zum Problem oder Vorschlag hinzu.
    validations:
      required: false