@startuml "DispenseRequest_Confirmation_Class"
!define RECTANGLE class

RECTANGLE "MessageHeader" as MH {
    +eventCode: #eRezept_Rezeptanforderung;Abgabebestaetigung
    +focus: Reference<ERPServiceRequestDispenseRequest>
}


RECTANGLE "ServiceRequest" as SR {
    +identifier:requestId: string
    +basedOn: Reference<ERPServiceRequestMedicationRequest>
    +status: #completed
    +intent: #filler-order
    +code: #dispense-request
    +subject: Reference<Patient>
    +occurrence: dateTime
    +authoredOn: Date
    +note: String
}

RECTANGLE "ERPServiceRequestMedicationRequest" as MR {
    +dispenseRequest.quantity: Quantity
    +medicationReference: Reference<KBV_Medication>
}

RECTANGLE "ERPServiceRequestPatient" as P {
    +name: String
    +identifier:kvnr: String
    +birthDate: Date
}

MH .down.> SR : .focus 1..*
SR .down.> P : .subject 1..1
SR .right.> MR : .basedOn 1..1
@enduml
