@startuml "PrescriptionRequest_Confirmation_Class"
!define RECTANGLE class

RECTANGLE "MessageHeader" as MH {
    +eventCode: #eRezept_Rezeptanforderung;Rezeptanfrage
    +focus: Reference<ERPServiceRequestPrescriptionRequest>
}


RECTANGLE "ServiceRequest" as SR {
    +identifier:requestId: string
    +basedOn: Reference<ERPServiceRequestMedicationRequest>
    +status: #completed
    +intent: #order
    +code: #prescription-request
    +subject: Reference<Patient>
    +occurrence: dateTime
    +authoredOn: Date
    +note: String
}

RECTANGLE "ERPServiceRequestMedicationRequest" as MR {
    +extension:PriorPrescriptionID: String
    +extension:requestMVO.extension:Kennzeichen: boolean
    +dispenseRequest.quantity: Quantity
    +medicationReference: Reference<KBV_Medication>
}

RECTANGLE "ERPServiceRequestPatient" as P {
    +name: String
    +identifier:kvnr: String
    +birthDate: Date
}

RECTANGLE "ERPServiceRequestPractitioner" as PR {
    +name: String
    +identifier:ANR: String
}

MH .down.> SR : .focus 1..*
SR .down.> P : .subject 1..1
SR .right.> MR : .basedOn 1..1
SR .down.> PR : .performer 1..1
@enduml
