@startuml

skinparam rectangle {
    roundCorner<<Concept>> 54
}

rectangle "Rezeptanforderungen Mappings (fachlich)" <<Concept>> {
    rectangle Rezeptanforderung_Storno #BUSINESS
}

rectangle "Nachrichten-ID der Rezeptanforderung" as Nachrichten_ID
rectangle "Begründung für Storno" as Stornierungsgrund


Rezeptanforderung_Storno *-- Nachrichten_ID
Rezeptanforderung_Storno o-- Stornierungsgrund

@enduml