@startuml
autonumber "<b>[0]"
participant Pflegeeinrichtung as PE #LightBlue
participant Arzt as A #LightYellow
participant "E-Rezept\nFachdienst" as FD #LightSalmon

activate PE
PE -> A++: <b>Prescription_ServiceRequest \n.status = active \n.basedOn = MEDREQ_Medication_Request
A <-> FD: E-Rezept einstellen
A -> PE--: <b>Prescription_ServiceRequest \n.status = completed \n.basedOn = KBV_Prescription
@enduml