@startuml

skinparam rectangle {
    roundCorner<<Concept>> 54
}

rectangle "Mapping: Rezeptanforderung_Ablehnung (fachlich)" <<Concept>> {
    rectangle Rezeptanforderung_Ablehnung #BUSINESS
}

rectangle "Nachrichten-ID der Rezeptanforderung" as Nachrichten_ID
rectangle "Grund für Ablehnung" as Ablehnungsgrund

Rezeptanforderung_Ablehnung *-- Nachrichten_ID
Rezeptanforderung_Ablehnung o-- Ablehnungsgrund

@enduml