@startuml

'top to bottom direction

'skinparam linetype ortho
hide circle
hide methods

'object "Fachliche \nInformationseinheit" as Businessobject #BUSINESS

class "Rezeptanforderung" as Rezeptanforderung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Prioritaet
    #Adressat_der_Rezeptanforderung
    #Adressat_der_Rezeptuebermittlung
    #Patienteninformationen
    #Vorheriges_Rezept
    ..medizinische Informationen..
    #Praeparat
    #Bedarfsbegruendung
    #Restreichweite
    ..ergänzende Informationen..
    #Freitext
}

class "Rezeptanforderung_Bestätigung" as Rezeptanforderung_Bestätigung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
    #Hinweise_fuer_Empfaenger
    ..ergänzende Informationen..
    #Freitext
}


class "Rezeptanforderung_Storno" as Rezeptanforderung_Storno #BUSINESS {
    ..administrative Informationen..
    #Vorgangs-ID
    #Begründung der Stornierung
}

Rezeptanforderung_Storno -up- Rezeptanforderung: revidiert >
Rezeptanforderung_Bestätigung -left- Rezeptanforderung: beantwortet >

@enduml