@startuml

'top to bottom direction

'skinparam linetype ortho
hide circle
hide methods

class "Rezeptanforderung" as Rezeptanforderung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Fall_ID
    #Patienten_ID
    #Prioritaet
    #Adressat_der_Rezeptanforderung
    #Adressat_der_Rezeptuebermittlung
    #Patienteninformationen
    #Vorheriges_Rezept
    ..medizinische Informationen..
    #Praeparat / Zubereitung
    #Bedarfsbegruendung
    ..ergänzende Informationen..
    #Freitext
}

class "Rezeptanforderung_Rezeptübermittlung" as Rezeptanforderung_Rezeptübermittlung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Fall_ID
    #Patienten_ID
    #ERezept_Access_Code
    #ERezept_Task_ID
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
    #Hinweise_fuer_Empfaenger
    ..ergänzende Informationen..
    #Unstrukturierter_Dateianhang
    #Freitext
}

class "Rezeptanforderung_Storno" as Rezeptanforderung_Storno #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Fall_ID
    #Patienten_ID
    ..medizinische Informationen..
    #Begruendung_der_Stornierung
    ..ergänzende Informationen..
    #Freitext
}


Rezeptanforderung_Storno -up- Rezeptanforderung: revidiert >
Rezeptanforderung_Rezeptübermittlung -up- Rezeptanforderung: beantwortet >

@enduml