@startuml


skinparam maxMessageSize 200

box "Rezeptmanagement" #White
    actor "Pflegeeinrichtung" as Pflegeeinrichtung
end box
actor "Verordnender \nLeistungserbringer" as Arztpraxis
actor Apotheke

title Rezeptanforderungen durch Pflegeeinrichtungen (fachliche Sicht)
hide footbox
autonumber

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Medikamentabgabe|
    **lfd.Nr.** //Informationseinheit als Nachricht übermittelt//
    **lfd.Nr.** **sonstige Aktivität**
endlegend

Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//
note left
    Bedarfsgründe für Rezeptanforderung:
      1. wg. Dosierung (Dauermedikation)
      2. nach Vitalwertmessung
      3. nach Bedarf
end note

opt #LightPink Stornierung
    Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung_Storno//
    Arztpraxis ->x Arztpraxis: **Rezeptanforderung wird verworfen**
end

alt Rezeptanforderung liegt vor beim Verordnenden
    alt #PaleGreen Arzt ist einverstanden 
        alt Direktübermittlungswunsch bei Pflegeeinrichtung
        Arztpraxis ->> Apotheke: //Dispensieranforderung_Rezeptübermittlung//
        else Pflegeeinrichtung entscheidet selbst über Übermittlung
        Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Bestätigung//
        Pflegeeinrichtung ->> Apotheke: //Dispensieranforderung_Rezeptübermittlung//
        end
        Apotheke ->> Pflegeeinrichtung: **Medikamentbelieferung**
        Apotheke ->> Pflegeeinrichtung: //Dispensieranforderung_Bestätigung//
    else #LightPink Arzt lehnt ab
        Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Storno//
    end
end

@enduml