@startuml

left to right direction

'skinparam linetype ortho
hide circle
hide methods


class "Rezeptanforderung_Rezeptuebermittlung" as Rezeptanforderung_Rezeptuebermittlung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #ERezept_Access_Code
    #ERezept_Task_ID
    '#Veränderungskennzeichen zur Ursprungsanfrage
    #Veraenderungskennzeichen
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
    #Hinweise_fuer_Empfaenger
    ..ergänzende Informationen..
    #Unstrukturierter_Dateianhang
    #Freitext
}

class "Strukturierter_Verordnungsdatensatz" as Strukturierter_Verordnungsdatensatz #BUSINESS {
    #Verordnungsinhalt
    #Verschreibender_Leistungserbringer
    #Betroffener_Versicherter
    #Abgebender_Leistungserbringer
    #Medikamentverabreichende_Institution
}

Rezeptanforderung_Rezeptuebermittlung::Strukturierter_Verordnungsdatensatz *-- Strukturierter_Verordnungsdatensatz



@enduml