@startuml


skinparam maxMessageSize 300

title Ablauf für Rezeptabgabe parenteraler Zubereitungen
hide footbox
autonumber


actor "Apotheke\n(Taxierungssoftware, Zytostatika-Programm)" as AVS
actor "Verordnender \nLeistungserbringer" as Arzt

participant "Primärsystem" as Arzt


legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Zubereitungs-/Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Zubereitungs-/Medikamentabgabe|
    **lfd.Nr.** //Informationseinheit als Nachricht übermittelt//
    **lfd.Nr.** **sonstige Aktivität**
endlegend

?-> AVS: Start der \nZubereitung

AVS ->> AVS: Zubereitungsdaten

AVS ->> Arzt: //Rezeptanforderung//

break #LightPink Stornierung notwendig
    AVS ->> Arzt: //Rezeptanforderung_Storno//
    Arzt ->x Arzt: **Rezeptanforderung wird verworfen**
    Arzt ->> AVS: //Rezeptanforderung_Storno//
end

alt #PaleGreen Arzt stimmt Rezeptanforderung zu
    ref over Arzt, Arzt #lightyellow
        E-Rezept einstellen
    end ref
    Arzt ->> AVS: //Rezeptanforderung_Rezeptübermittlung//
else #LightPink Arzt lehnt Rezeptanforderung ab
    Arzt ->> AVS: //Rezeptanforderung_Storno//

end

@enduml