@startuml


skinparam maxMessageSize 200

box "Rezeptmanagement" #White
    actor "Pflegeeinrichtung" as Pflegeeinrichtung
end box
actor "Verordnender \nLeistungserbringer" as Arztpraxis
actor Apotheke
actor Versicherter

title Rezeptanforderungen durch Pflegeeinrichtungen mit Abholung durch Versicherten (fachliche Sicht)
hide footbox
autonumber

legend bottom right
    __Legende__
    |<#PaleGreen> Ergebnis: Medikamentabgabe|
    |<#LightPink> Ergebnis: keine Medikamentabgabe|
    **lfd.Nr.** //Informationseinheit als Nachricht übermittelt//
    **lfd.Nr.** **sonstige Aktivität**
endlegend

Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung//
note left
    Bedarfsgründe für Rezeptanforderung:
      1. wg. Dosierung (Dauermedikation)
      2. nach Vitalwertmessung
      3. nach Bedarf
end note

opt #LightPink Stornierung
    Pflegeeinrichtung ->> Arztpraxis: //Rezeptanforderung_Storno//
    Arztpraxis ->x Arztpraxis: **Rezept-**\n**anforderung** \n**wird verworfen**
end


alt Rezeptanforderung liegt vor beim Verordnenden
    alt #PaleGreen Arzt ist einverstanden 
        Arztpraxis ->> Pflegeeinrichtung: Rezeptanforderung_Rezeptübermittlung
        Pflegeeinrichtung --> Versicherter: opt. Benachrichtigung über Ausstellung des E-Rezepts
        Versicherter ->> Apotheke: **Medikamentabholung gg. Rezeptvorlage**
        note left
            möglich via
              1. E-Rezept-App
              2. Vorlage der eGK in der Apotheke
              3. Papierausdruck
        end note
    else #LightPink Arzt lehnt ab
        Arztpraxis ->> Pflegeeinrichtung: //Rezeptanforderung_Storno//
    end
end

@enduml