@startuml

'top to bottom direction

'skinparam linetype ortho
hide circle
hide methods

class "Fachliche \nInformationseinheit" as Businessobject #BUSINESS

class "Rezeptanforderung" as Rezeptanforderung #BUSINESS
class "Rezeptanforderung_Storno" as Rezeptanforderung_Storno #BUSINESS
class "Rezeptanforderung_Rezeptübermittlung" as Rezeptanforderung_Rezeptübermittlung #BUSINESS
class "Dispensieranforderung_Rezeptübermittlung" as Dispensieranforderung_Rezeptübermittlung #BUSINESS

class "FHIR-Bundle" as Fhirbundle #APPLICATION
class "KIM-Nachricht" as KIMNachricht #TECHNOLOGY

class "Empfänger" as Empfaenger #TECHNOLOGY
class "Absender" as Absender #TECHNOLOGY
class "E-Rezept" as ERezept
class "E-Rezept-Token" as ERezepttoken
class "Verordnung" as Medication
class "Versicherter" as Versicherter
class "Dispensierung" as Dispensierung

Rezeptanforderung_Rezeptübermittlung -left|> Businessobject: ist eine
Rezeptanforderung -down|> Businessobject: ist eine
Rezeptanforderung_Storno -left|> Businessobject: ist eine
Rezeptanforderung_Storno -down|> Businessobject: ist eine
Dispensieranforderung_Rezeptübermittlung -|> Businessobject: ist eine

Rezeptanforderung -up- "1..1" Versicherter: bezieht sich auf >
Rezeptanforderung_Storno -- "1..1" Rezeptanforderung: revidiert >
Rezeptanforderung_Storno -- "1..1" Rezeptanforderung: beantwortet >
Rezeptanforderung_Rezeptübermittlung -- "1..1" Rezeptanforderung: beantwortet >
Rezeptanforderung_Rezeptübermittlung -- "1..1" ERezepttoken: enthält >
Dispensieranforderung_Rezeptübermittlung -- "1..1" ERezepttoken: enthält >
Dispensieranforderung_Rezeptübermittlung -- "1..1" Dispensierung: enthält >
Dispensieranforderung_Rezeptübermittlung -- "1..1" Rezeptanforderung_Rezeptübermittlung: aggregiert >
ERezepttoken -right- "1..1" ERezept: referenziert auf >
ERezept -right- "1..1" Medication: enthält >

KIMNachricht -- "1..1" Empfaenger: hat >
KIMNachricht -- "1..1" Absender: hat >

Businessobject -right- "1..1" Fhirbundle: wird repräsentiert als >

Fhirbundle "1..1" -- "0..1" KIMNachricht: ist enthalten in >
Rezeptanforderung -- "1..1" ERezept: bezieht sich auf >

@enduml