@startuml

'top to bottom direction

'skinparam linetype ortho
hide circle
hide methods

class "Rezeptanforderung" as Rezeptanforderung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Prioritaet
    #Adressat_der_Rezeptanforderung
    #Adressat_der_Rezeptuebermittlung
    #Patienteninformationen
    #Vorheriges_Rezept
    ..medizinische Informationen..
    #Praeparat
    #Bedarfsbegruendung
    #Restreichweite
    ..ergänzende Informationen..
    #Freitext
}

class "Rezeptanforderung_Storno" as Rezeptanforderung_Storno #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Begruendung_der_Stornierung
    ..ergänzende Informationen..
    #Freitext
}

class "Rezeptanforderung_Bestätigung" as Rezeptanforderung_Bestätigung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #ERezept_Access_Code
    #ERezept_Task_ID
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
    #Hinweise_fuer_Empfaenger
    ..ergänzende Informationen..
    #Freitext
}

class "Dispensieranforderung_Rezeptübermittlung" as Dispensieranforderung_Rezeptübermittlung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #ERezept_Access_Code
    #ERezept_Task_ID
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
}

class "Dispensieranforderung_Bestätigung" as Dispensieranforderung_Bestätigung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #ERezept_Access_Code
    #ERezept_Task_ID
    ..medizinische Informationen..
    #Strukturierter_Verordnungsdatensatz
    #Strukturierter_Dispensierungsdatensatz
}

Rezeptanforderung_Storno -up- Rezeptanforderung: revidiert >
Rezeptanforderung_Bestätigung -up- Rezeptanforderung: beantwortet >
Dispensieranforderung_Bestätigung -- Dispensieranforderung_Rezeptübermittlung: beantwortet >
Dispensieranforderung_Rezeptübermittlung -- Rezeptanforderung_Bestätigung: bezieht sich auf >

@enduml