@startuml

skinparam sequence {
    ArrowColor black
    ActorBorderColor black
    LifeLineBorderColor darkgray
    LifeLineBackgroundColor #ffffc0

    ParticipantBorderColor black
    ParticipantBackgroundColor #ffffc0
    ParticipantFontName Arial
    ParticipantFontSize 14
    ParticipantFontColor black

    ActorBackgroundColor #ffffc0
    ActorFontColor #303030
    ActorFontSize 14
    ActorFontName Arial

    BoxBorderColor gray
}

skinparam maxMessageSize 400
title Versenden von Verordnungs- und Dispensierinformationen einer \nerfolgreichen Rezeptanforderung durch die liefernde Apotheke
hide footbox
autonumber

participant "AVS" as PS #BUSINESS
participant "KIM \nClientmodul" as Kim_cm #TECHNOLOGY
participant "KIM \nFachdienst" as Kim_fd #TECHNOLOGY



PS o-> PS++: $close-Action durchgeführt UND Rezeptvorgang mit gleicher Rezept_ID vorhanden()

PS -> PS++: Vorgang ermitteln(Rezept_ID)
return :Vorgang

PS -> PS++: KIM-Adresse der Pflegeeinrichtung übernehmen(Vorgang.GEM_PR_ERP_MEDREQ_RequestBundle. GEM_PR_ERP_MEDREQ_Organization[Bundle.entry=RequestingOrganization]. telecom.value)
return :gültige KIM-Adresse



PS -> PS++: Verordnungsdatensatz aus E-Rezept-FHIR-Bundle.patientReceipt übernehmen(Rezept_ID)
return :Verordnungsdatensatz

PS -> PS++: MedicationDispense aus $close-Action übernehmen(Rezept_ID)
return :Dispensierungsdatensatz

PS -> PS++: FHIR-Bundle "GEM_PR_ERP_MEDREQ_DispenseInformationBundle" generieren(Verordnungsdatensatz, Dispensierungsdatensatz)
return :GEM_PR_ERP_MEDREQ_DispenseInformationBundle

PS -> PS++: Mail-MIME-Attachment generieren(GEM_PR_ERP_MEDREQ_DispenseInformationBundle)
return :Mail-Attachment

PS -> PS++: Mail generieren(Mail-Attachment, gültige KIM-Adresse, X-KIM-Header-Information:= X-KIM-Dienstkennung="E-Rezept;Verordnung_Dispensierung;V1.0")
return :KIM-Mail

PS -> Kim_cm++#TECHNOLOGY: KIM-Mail senden mit GEM_PR_ERP_MEDREQ_DispenseInformationBundle als Payload(KIM-Mail)

group #LightYellow KIM Standardkommunikation
ref over Kim_cm, Kim_fd #lightyellow
    KIM-Mail senden
end ref

return :Status
end group



@enduml