@startuml

left to right direction

'skinparam linetype ortho
hide circle
hide methods

class "Rezeptanforderung" as Rezeptanforderung #BUSINESS {
    ..administrative Informationen..
    #Vorgangs_ID
    #Prioritaet
    #Adressat_der_Rezeptanforderung
    #Adressat_der_Rezeptuebermittlung
    #Patienteninformationen
    #Vorheriges_Rezept
    ..medizinische Informationen..
    #Praeparat
    #Bedarfsbegruendung
    #Restreichweite
    ..ergänzende Informationen..
    #Freitext
}

class "Adressat_der_Rezeptuebermittlung" as Anfordernde_Pflegeeinrichtung #BUSINESS {
    #Telematik_ID
    #Empfaenger_Typ
}

class "Patienteninformationen" as Patienteninformationen #BUSINESS {
    #KVNR
    #Name
    #Geburtstag
}

class "Praeparat" as Praeparat #BUSINESS {
    #Bezeichnung
    #Packungsgroesse
    #Dosierung
}

class "Restreichweite" as Restreichweite #BUSINESS {
    #Anzahl_Resteinheiten
    #Restreichweitendatum
}

class "Adressat_der_Rezeptanforderung" as Arztinformationen #BUSINESS {
    #Telematik_ID
    #Name
    #Ort
    #Telefonnummer
}

Rezeptanforderung::Adressat_der_Rezeptuebermittlung *-- Anfordernde_Pflegeeinrichtung
Rezeptanforderung::Patienteninformationen *-- Patienteninformationen
Rezeptanforderung::Praeparat *-- Praeparat
Rezeptanforderung::Vorheriges_Rezept --> Praeparat: Verweis >
Rezeptanforderung::Restreichweite o-- Restreichweite
Rezeptanforderung::Adressat_der_Rezeptanforderung *-- Arztinformationen


@enduml