@startuml

skinparam sequence {
    ArrowColor black
    ActorBorderColor black
    LifeLineBorderColor darkgray
    LifeLineBackgroundColor #ffffc0

    ParticipantBorderColor black
    ParticipantBackgroundColor #ffffc0
    ParticipantFontName Arial
    ParticipantFontSize 14
    ParticipantFontColor black

    ActorBackgroundColor #ffffc0
    ActorFontColor #303030
    ActorFontSize 14
    ActorFontName Arial
    
    BoxBorderColor gray
}

skinparam maxMessageSize 250
title Ablehnung zu einer Rezeptanforderung übermitteln durch LEI des Verordnenden
hide footbox
autonumber

actor "Verordnender Leistungserbringer" as Arzt
participant "Primärsystem verordnender \nLeistungserbringerinstitution" as PS_Arzt
participant "KIM \nClientmodul" as Kim_cm #TECHNOLOGY
participant "KIM \nFachdienst" as Kim_fd #TECHNOLOGY

Arzt -> PS_Arzt++: Rezeptanforderung bearbeiten()

PS_Arzt -> Arzt++: Vorgang präsentieren(Vorgang, Medikationsabweichung)
    note right
        Präsentation z.B. in
        Form einer Signaturliste
    end note

Arzt -> Arzt: vorliegende Rezeptanforderung ablehnen(Rezeptanforderung)
    note right
        Ablehnung z.B. aufgrund einer festgestellten Medikationsabweichung
    end note
Arzt --> PS_Arzt++: :Rezeptanforderung, :Ablehnung
deactivate Arzt

PS_Arzt -> PS_Arzt++: KIM-Adresse des Empfängers übernehmen(Vorgang.GEM_PR_ERP_MEDREQ_RequestBundle. GEM_PR_ERP_MEDREQ_Organization[Bundle.entry=RequestingOrganization]. telecom.value)
return :gültige KIM-Adresse

PS_Arzt -> PS_Arzt++: FHIR-Bundle "GEM_PR_ERP_MEDREQ_CancellationBundle" generieren(Vorgang.Vorgangs_ID, Ablehnung.Ablehnungsgrund)
return :GEM_PR_ERP_MEDREQ_CancellationBundle

PS_Arzt -> PS_Arzt++: Mail-MIME-Attachment generieren(GEM_PR_ERP_MEDREQ_CancellationBundle)
return :Mail-Attachment

PS_Arzt -> PS_Arzt++: Mail generieren(Mail-Attachment, gültige KIM-Adresse, X-KIM-Header-Information:= X-KIM-Dienstkennung="E-Rezept;Rezeptanforderung_Ablehnung;V1.0")
return :KIM-Mail

PS_Arzt -> Kim_cm++#TECHNOLOGY: KIM-Mail senden mit "GEM_PR_ERP_MEDREQ_CancellationBundle" Bundle als Payload(KIM-Mail)


group #LightYellow KIM Standardkommunikation
ref over Kim_cm, Kim_fd #lightyellow
    KIM-Mail senden
end ref

return :Status
end group


@enduml