@startuml
autonumber "<b>[0]"
participant Pflegeeinrichtung as PE #LightBlue
participant Apotheke as A #LightGreen
participant "E-Rezept\nFachdienst" as FD #LightSalmon

activate PE
PE -> A++: <b>Dispense_ServiceRequest \n.status = active \n.basedOn = KBV_Prescription \n.extension:EPrescriptionToken = E-Rezept Token
A <-> FD: E-Rezept einlösen
A -> PE--: <b>Dispense_ServiceRequest \n.status = completed \n.basedOn = KBV_Prescription \n.extension:EPrescriptionToken = E-Rezept Token
@enduml