@startuml UC1_2
autonumber 6 "<b>[0]"
participant Pflegeeinrichtung as PE #LightBlue
participant Apotheke as A #LightGreen
participant "E-Rezept-Fachdienst" as FD #LightSalmon

activate PE
PE -> A++: <b>Dispensieranforderung_Rezeptübermittlung \n<i>ERPServiceRequestDispenseRequest \n.status = #active \n.basedOn = KBV_PR_ERP_Prescription \n.extension:EPrescriptionToken = E-Rezept Token
A <-> FD: E-Rezept einlösen
A -> PE--: <b>Dispensieranforderung_Bestätigung \n<i>ERPServiceRequestDispenseRequest \n.status = #completed \n.basedOn = KBV_Prescription \n.extension:EPrescriptionToken = E-Rezept Token
@enduml